# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-14 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_slick_slider', '0003_auto_20180201_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='slickslider',
            name='arrows',
            field=models.BooleanField(default=True, verbose_name='Arrows'),
        ),
        migrations.AddField(
            model_name='slickslider',
            name='dots',
            field=models.BooleanField(default=True, verbose_name='Dots'),
        ),
        migrations.AddField(
            model_name='slickslider',
            name='slides_to_show',
            field=models.PositiveIntegerField(default=1, verbose_name='Slides to show'),
        ),
        migrations.AddField(
            model_name='slickslider',
            name='speed',
            field=models.PositiveIntegerField(default=300, verbose_name='Speed (ms)'),
        ),
        migrations.AlterField(
            model_name='slicksliderimage',
            name='caption_text',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='caption text'),
        ),
    ]
