# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-15 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_slick_slider', '0004_auto_20190314_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='slickslider',
            name='autoplay',
            field=models.BooleanField(default=True, verbose_name='Autoplay'),
        ),
        migrations.AddField(
            model_name='slickslider',
            name='autoplay_speed',
            field=models.PositiveIntegerField(default=3000, verbose_name='Autoplay speed (ms)'),
        ),
    ]
