# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-19 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_slick_slider', '0005_auto_20190315_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slickslider',
            name='autoplay_speed',
            field=models.PositiveIntegerField(default=1500, verbose_name='Autoplay speed (ms)'),
        ),
        migrations.AlterField(
            model_name='slickslider',
            name='settings',
            field=jsonfield.fields.JSONField(blank=True, default={}, editable=False, help_text='Check <a href="http://kenwheeler.github.io/slick/" target="_blank">Slick Documentation</a> for possible settings <br>Use JSON format and check the errors in the editor<br>You can also use online JSON validators', null=True, verbose_name='slick settings'),
        ),
    ]
