# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-29 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'djangocms_slick_slider', '0007_slickslider_image_height'), (b'djangocms_slick_slider', '0008_auto_20190329_1627')]

    dependencies = [
        ('djangocms_slick_slider', '0006_auto_20190319_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='slickslider',
            name='image_height',
            field=models.CharField(default='200px', max_length=10, verbose_name='Height'),
        ),
    ]
